name = "REPLACE_PKG"
uuid = "REPLACE_UUID"
authors = ["Patrick Armstrong <u6096820@anu.edu.au> and contributors"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
OLUtils = "c0b1955d-4702-4680-a946-720482e78a48"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
