name = "REPLACE_PKG"
uuid = "a50c839e-1b84-4575-b48f-4fda80ec5e07"
authors = ["Patrick Armstrong <patrick.armstrong@anu.edu.au> and contributors"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BetterInputFiles = "c0b1955d-4702-4680-a946-720482e78a48"
StatProfilerHTML = "a8a75453-ed82-57c9-9e16-4cd1196ecbf5"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
julia = "^1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
